### PR TITLE
Add remote_credentials to environment when initializing repositories

### PR DESCRIPTION
**Pull request by maloddon**
This is a first fix for #21, but does not uppercases `remote_credentials ` keys for now, as done there : https://github.com/paulfantom/ansible-restic/blob/a45f6c7575f67d2fc681bb957ce44b488b202b0c/templates/restic.cron.j2#L10

### CODE REVIEW

**Comment by paulfantom** [comment]
If it doesn't do uppercasing, please add some checking if keys are uppercase in [tasks/preflight.yml](https://github.com/paulfantom/ansible-restic/blob/master/tasks/preflight.yml).

**Comment by paulfantom** [comment]
Also `remote_credentials` isn't a hard requirement so there are cases where it isn't defined. That's why in template there is this check: 
https://github.com/paulfantom/ansible-restic/blob/master/templates/restic.cron.j2#L8

Without it role would fail when no remote credentials are used.

**Comment by maloddon** [comment]
Great, thanks for feedback. I will try to push some fixes asap !

**Comment by TheLastProject** [comment]
I ran into this issue as well. Could it perhaps be merged even though there has been no preflight check added yet and just have a README note to capitalize the remote_credentials keys?

**Pull request merged**
