### PR TITLE
Add support for letting restic run certain commands with sudo

### PR DESCRIPTION
**Pull request by TheLastProject**
Sometimes, you will need to run an application's backup output tool as root. This change allows you to selectively whitelist some commands, so that you do not have to run restic as root in full.

### CODE REVIEW

**Comment by TheLastProject** [comment]
This is tested and works well, causing no regressions. Just not merging it myself to not be rude :)

**Comment by paulfantom** [comment]
@TheLastProject you are doing more work in this repo than I do :smile: Merge when you think code is ok, I won't mind :smile:

**Comment by TheLastProject** [comment]
Sounds good. Also, maybe time for a new release? Restic 0.9.4 being the default now and all :)

**Comment by paulfantom** [comment]
CI needs to be fixed first, without it I cannot do a release :(

I'll take a look at it today or tomorrow.

**Pull request merged**
