### PR TITLE
Integration of a script that check the date of the last backup

### PR DESCRIPTION
**Pull request by kalos**
Return a warning/critical alert for nagios/icinga.

### CODE REVIEW

**Comment by TheLastProject** [comment]
May I suggest using restic's JSON output at least? The normal output isn't meant for scripts as far as I know

**Comment by kalos** [comment]
I think it is not worth using json (and therefore jq, for bash) only to extrapolate the date of the last backup.

Even with json you need to create a script to return the alert.

**Comment by TheLastProject** [comment]
Personally, I'd rather see jq added as a dependency than parsing an output style meant for human conversion that may easily change between releases, but it's @paulfantom's project so let's wait for his input :)

**Comment by paulfantom** [comment]
I am also in favor of `jq`

**Comment by kalos** [comment]
What would change with jd, are just the following lines:
```
SNAPS="$($RESTIC snapshots --compact --no-lock -H $RESTIC_HOST)"
[...]
LAST=$(sed 1,2d <<< $SNAPS | head -n -2 | tail -n 1)
COUNT=$(tail -n 1 <<< $SNAPS | cut -d " " -f 1)
```
Which are however very simple to read / modify.
A script would still be needed to manage the alerts. All the logic would remain unchanged.

Furthermore the script has already been tested by several people since it is taken directly from https://github.com/binarybucks/restic-tools .
I made only a few changes to integrate it into the ansible role.

Frankly, I prefer not to add a dependency on my servers / hosts in this case.

For more complex operations, like extracting paths, excludes, etc., json is the only way, but for such a simple operation I prefer to use the shell.

If you do not agree, please also reject the request.

I wish you all a good day.

**Comment by paulfantom** [comment]
I am putting adding ANY bash scripts to this repository on hold. Purpose of this repository is to install and configure restic itself and not to develop a custom wrapper around it. 

For more information on possible role future and solutions to second day operations go to #57.

**Comment by kalos** [comment]
I continue to fix my version of this role, expectant for the new paulfantom/ansible-restic role version with complete restic wrapper (runrestic?)

my fork: https://github.com/kalos/ansible-restic
Thanks Paweł

**Pull request closed without merging**
