### PR TITLE
Add helpers for easier backup restoring

### PR DESCRIPTION
**Pull request by TheLastProject**
I like this role, but when playing with it I noticed that if you actually want to restore a backup, manage snapshots or anything else, you'll have to hunt down the environment variables in the cronjob files. If there's anything I learned, it's that when you need backups there's generally a sense of panic, so making them easier to reach seemed like a helpful addition.

This pull request adds some helper scripts to restic_user's home directory in their $PATH, with the same naming scheme as the cronjobs. This means that if you have a restic repo that you named "testrepo", you could easily restore backups of it by su'ing into the restic_user and running `restic-testrepo` commands (provided you set a restic_user and changed the restic_shell to something usable).

### CODE REVIEW

**Comment by paulfantom** [comment]
I like it! 

Since we are already restricting access to those scripts, maybe it will be better to put them in `{{ restic_install_path }}` not in `{{ restic_home }}/bin`. This way we don't need to create additional directory and manipulate $PATH.

It would be also nice to document usage of this helper script.

**Comment by TheLastProject** [comment]
Makes sense to me. I also hope I hereby added sufficient documentation, or is there anything you feel is still missing?

**Comment by TheLastProject** [comment]
Okay, after working on this a bit more after seeing #34 I hereby consider this feature done, it works quite reliably from my testing too.

**Comment by paulfantom** [comment]
Great job! Thank you! :+1:

**Pull request merged**
